
DROP TABLE IF EXISTS employee;
DROP TABLE IF EXISTS department;
DROP TABLE IF EXISTS designation;

CREATE TABLE department (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(100)
);

CREATE TABLE designation (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title varchar(100)
);

CREATE TABLE employee (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name varchar(100),
    last_name varchar(100),
    birth_date date,
    hire_date date,
    salary money,
    designation_id integer REFERENCES department(id),
    department_id integer REFERENCES designation(id)
);
